<?php

declare(strict_types=1);

/**
 * FR-MD-03 reference data: the 9 GHS pictogram classes and the standard UN GHS
 * hazard (H) / precautionary (P) statement codes with their official English
 * wording (Rev.9). Static reference data, not user-editable — kept as config,
 * not a seeded table. User-approved 2026-09-01: English official text only, no
 * bundled Thai translation (no verified official government source at hand for
 * ~160 safety-critical statements — better to show none than a wrong one).
 */
return [

    'pictograms' => [
        'GHS01' => 'Explosive',
        'GHS02' => 'Flammable',
        'GHS03' => 'Oxidizing',
        'GHS04' => 'Compressed Gas',
        'GHS05' => 'Corrosive',
        'GHS06' => 'Toxic',
        'GHS07' => 'Harmful / Irritant',
        'GHS08' => 'Health Hazard',
        'GHS09' => 'Environmental Hazard',
    ],

    'hazard_statements' => [
        // Physical hazards
        'H200' => 'Unstable explosives',
        'H201' => 'Explosive; mass explosion hazard',
        'H202' => 'Explosive; severe projection hazard',
        'H203' => 'Explosive; fire, blast or projection hazard',
        'H204' => 'Fire or projection hazard',
        'H205' => 'May mass explode in fire',
        'H220' => 'Extremely flammable gas',
        'H221' => 'Flammable gas',
        'H222' => 'Extremely flammable aerosol',
        'H223' => 'Flammable aerosol',
        'H224' => 'Extremely flammable liquid and vapour',
        'H225' => 'Highly flammable liquid and vapour',
        'H226' => 'Flammable liquid and vapour',
        'H228' => 'Flammable solid',
        'H240' => 'Heating may cause an explosion',
        'H241' => 'Heating may cause a fire or explosion',
        'H242' => 'Heating may cause a fire',
        'H250' => 'Catches fire spontaneously if exposed to air',
        'H251' => 'Self-heating; may catch fire',
        'H252' => 'Self-heating in large quantities; may catch fire',
        'H260' => 'In contact with water releases flammable gases which may ignite spontaneously',
        'H261' => 'In contact with water releases flammable gas',
        'H270' => 'May cause or intensify fire; oxidizer',
        'H271' => 'May cause fire or explosion; strong oxidizer',
        'H272' => 'May intensify fire; oxidizer',
        'H280' => 'Contains gas under pressure; may explode if heated',
        'H281' => 'Contains refrigerated gas; may cause cryogenic burns or injury',
        'H282' => 'Extremely flammable chemical under pressure: may explode if heated',
        'H283' => 'Flammable chemical under pressure: may explode if heated',
        'H284' => 'Chemical under pressure: may explode if heated',
        'H290' => 'May be corrosive to metals',

        // Health hazards
        'H300' => 'Fatal if swallowed',
        'H301' => 'Toxic if swallowed',
        'H302' => 'Harmful if swallowed',
        'H303' => 'May be harmful if swallowed',
        'H304' => 'May be fatal if swallowed and enters airways',
        'H305' => 'May be harmful if swallowed and enters airways',
        'H310' => 'Fatal in contact with skin',
        'H311' => 'Toxic in contact with skin',
        'H312' => 'Harmful in contact with skin',
        'H313' => 'May be harmful in contact with skin',
        'H314' => 'Causes severe skin burns and eye damage',
        'H315' => 'Causes skin irritation',
        'H316' => 'Causes mild skin irritation',
        'H317' => 'May cause an allergic skin reaction',
        'H318' => 'Causes serious eye damage',
        'H319' => 'Causes serious eye irritation',
        'H320' => 'Causes eye irritation',
        'H330' => 'Fatal if inhaled',
        'H331' => 'Toxic if inhaled',
        'H332' => 'Harmful if inhaled',
        'H333' => 'May be harmful if inhaled',
        'H334' => 'May cause allergy or asthma symptoms or breathing difficulties if inhaled',
        'H335' => 'May cause respiratory irritation',
        'H336' => 'May cause drowsiness or dizziness',
        'H340' => 'May cause genetic defects',
        'H341' => 'Suspected of causing genetic defects',
        'H350' => 'May cause cancer',
        'H351' => 'Suspected of causing cancer',
        'H360' => 'May damage fertility or the unborn child',
        'H361' => 'Suspected of damaging fertility or the unborn child',
        'H362' => 'May cause harm to breast-fed children',
        'H370' => 'Causes damage to organs',
        'H371' => 'May cause damage to organs',
        'H372' => 'Causes damage to organs through prolonged or repeated exposure',
        'H373' => 'May cause damage to organs through prolonged or repeated exposure',

        // Environmental hazards
        'H400' => 'Very toxic to aquatic life',
        'H410' => 'Very toxic to aquatic life with long lasting effects',
        'H411' => 'Toxic to aquatic life with long lasting effects',
        'H412' => 'Harmful to aquatic life with long lasting effects',
        'H413' => 'May cause long lasting harmful effects to aquatic life',
        'H420' => 'Harms public health and the environment by destroying ozone in the upper atmosphere',
    ],

    'precautionary_statements' => [
        // General
        'P101' => 'If medical advice is needed, have product container or label at hand',
        'P102' => 'Keep out of reach of children',
        'P103' => 'Read label before use',

        // Prevention
        'P201' => 'Obtain special instructions before use',
        'P202' => 'Do not handle until all safety precautions have been read and understood',
        'P210' => 'Keep away from heat, hot surfaces, sparks, open flames and other ignition sources. No smoking',
        'P211' => 'Do not spray on an open flame or other ignition source',
        'P212' => 'Avoid heating under confinement or reducing insensitiveness',
        'P220' => 'Keep away from clothing and other combustible materials',
        'P221' => 'Take any precaution to avoid mixing with combustibles',
        'P222' => 'Do not allow contact with air',
        'P223' => 'Keep away from any possible contact with water',
        'P230' => 'Keep wetted with an appropriate material',
        'P231' => 'Handle under inert gas',
        'P232' => 'Protect from moisture',
        'P233' => 'Keep container tightly closed',
        'P234' => 'Keep only in original container',
        'P235' => 'Keep cool',
        'P240' => 'Ground/bond container and receiving equipment',
        'P241' => 'Use explosion-proof electrical/ventilating/lighting equipment',
        'P242' => 'Use only non-sparking tools',
        'P243' => 'Take precautionary measures against static discharge',
        'P244' => 'Keep reduction valves free from grease and oil',
        'P250' => 'Do not subject to grinding/shock/friction',
        'P251' => 'Do not pierce or burn, even after use',
        'P260' => 'Do not breathe dust/fume/gas/mist/vapours/spray',
        'P261' => 'Avoid breathing dust/fume/gas/mist/vapours/spray',
        'P262' => 'Do not get in eyes, on skin, or on clothing',
        'P263' => 'Avoid contact during pregnancy/while nursing',
        'P264' => 'Wash exposed skin thoroughly after handling',
        'P270' => 'Do not eat, drink or smoke when using this product',
        'P271' => 'Use only outdoors or in a well-ventilated area',
        'P272' => 'Contaminated work clothing should not be allowed out of the workplace',
        'P273' => 'Avoid release to the environment',
        'P280' => 'Wear protective gloves/protective clothing/eye protection/face protection',
        'P281' => 'Use personal protective equipment as required',
        'P282' => 'Wear cold insulating gloves/face shield/eye protection',
        'P283' => 'Wear fire/flame resistant/retardant clothing',
        'P284' => 'Wear respiratory protection',
        'P285' => 'In case of inadequate ventilation wear respiratory protection',

        // Response
        'P301' => 'IF SWALLOWED',
        'P302' => 'IF ON SKIN',
        'P303' => 'IF ON SKIN (or hair)',
        'P304' => 'IF INHALED',
        'P305' => 'IF IN EYES',
        'P306' => 'IF ON CLOTHING',
        'P307' => 'IF exposed',
        'P308' => 'IF exposed or concerned',
        'P309' => 'IF exposed or if you feel unwell',
        'P310' => 'Immediately call a POISON CENTER or doctor/physician',
        'P311' => 'Call a POISON CENTER or doctor/physician',
        'P312' => 'Call a POISON CENTER or doctor/physician if you feel unwell',
        'P313' => 'Get medical advice/attention',
        'P314' => 'Get medical advice/attention if you feel unwell',
        'P315' => 'Get immediate medical advice/attention',
        'P320' => 'Specific treatment is urgent (see supplemental first aid instructions on this label)',
        'P321' => 'Specific treatment (see supplemental first aid instructions on this label)',
        'P322' => 'Specific measures (see supplemental first aid instructions on this label)',
        'P330' => 'Rinse mouth',
        'P331' => 'Do NOT induce vomiting',
        'P332' => 'If skin irritation occurs',
        'P333' => 'If skin irritation or rash occurs',
        'P334' => 'Immerse in cool water/wrap in wet bandages',
        'P335' => 'Brush off loose particles from skin',
        'P336' => 'Thaw frosted parts with lukewarm water. Do not rub affected area',
        'P337' => 'If eye irritation persists',
        'P338' => 'Remove contact lenses, if present and easy to do. Continue rinsing',
        'P340' => 'Remove person to fresh air and keep comfortable for breathing',
        'P341' => 'If breathing is difficult, remove person to fresh air and keep comfortable for breathing',
        'P342' => 'If experiencing respiratory symptoms',
        'P350' => 'Gently wash with plenty of soap and water',
        'P351' => 'Rinse cautiously with water for several minutes',
        'P352' => 'Wash with plenty of soap and water',
        'P353' => 'Rinse skin with water/shower',
        'P360' => 'Rinse immediately contaminated clothing and skin with plenty of water before removing clothes',
        'P361' => 'Remove/Take off immediately all contaminated clothing',
        'P362' => 'Take off contaminated clothing and wash it before reuse',
        'P363' => 'Wash contaminated clothing before reuse',
        'P370' => 'In case of fire',
        'P371' => 'In case of major fire and large quantities',
        'P372' => 'Explosion risk in case of fire',
        'P373' => 'Do NOT fight fire when fire reaches explosives',
        'P374' => 'Fight fire with normal precautions from a reasonable distance',
        'P375' => 'Fight fire remotely due to the risk of explosion',
        'P376' => 'Stop leak if safe to do so',
        'P377' => 'Leaking gas fire: Do not extinguish, unless leak can be stopped safely',
        'P380' => 'Evacuate area',
        'P381' => 'Eliminate all ignition sources if safe to do so',
        'P390' => 'Absorb spillage to prevent material damage',
        'P391' => 'Collect spillage',

        // Storage
        'P401' => 'Store in accordance with local/regional/national/international regulations',
        'P402' => 'Store in a dry place',
        'P403' => 'Store in a well-ventilated place',
        'P404' => 'Store in a closed container',
        'P405' => 'Store locked up',
        'P406' => 'Store in corrosive resistant container with a resistant inner liner',
        'P407' => 'Maintain air gap between stacks/pallets',
        'P410' => 'Protect from sunlight',
        'P411' => 'Store at temperatures not exceeding the manufacturer-specified limit',
        'P412' => 'Do not expose to temperatures exceeding 50 °C/122 °F',
        'P413' => 'Store bulk masses greater than the manufacturer-specified quantity at temperatures not exceeding the manufacturer-specified limit',
        'P420' => 'Store away from other materials',
        'P422' => 'Store contents in accordance with the manufacturer/supplier instructions',

        // Disposal
        'P501' => 'Dispose of contents/container in accordance with local/regional/national/international regulations',
    ],

];
