<?php

use App\Domain\Notification\Services\NotificationService;
use App\Domain\Reporting\Jobs\GenerateLedgerPdfExportJob;
use App\Domain\Reporting\Services\Fr03PdfService;
use App\Mail\NotificationMail;
use App\Models\Container;
use App\Models\LedgerExportRequest;
use App\Models\Notification;
use App\Models\Unit;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Queue;
use Illuminate\Support\Facades\Storage;

uses(RefreshDatabase::class);

/**
 * NFR-02: beyond LedgerExportController::ASYNC_ROW_THRESHOLD (5000) matching rows,
 * the PDF export is generated by GenerateLedgerPdfExportJob instead of inline.
 * Bulk-inserts synthetic stock_ledger rows directly (bypassing LedgerService) since
 * only the row *count* matters here, not real balances/hash-chain integrity.
 */
function seedManyLedgerRows(int $count): array
{
    $item = makeItem(['base_unit_id' => Unit::where('code', 'g')->value('id')]);
    $g = Unit::where('code', 'g')->firstOrFail();
    $creator = User::factory()->create();
    $container = Container::create([
        'item_id' => $item->id,
        'barcode' => 'BC-ASYNC-'.fake()->unique()->numerify('####'),
        'received_at' => now()->toDateString(),
        'initial_qty_base' => '0.000000',
        'remaining_qty_base' => '0.000000',
        'status' => 'SEALED',
    ]);

    $now = now();
    $rows = [];
    for ($i = 0; $i < $count; $i++) {
        $rows[] = [
            'item_id' => $item->id,
            'container_id' => $container->id,
            'txn_date' => $now->toDateString(),
            'txn_type' => 'RECEIVE',
            'qty_in_base' => '1.000000',
            'qty_out_base' => '0.000000',
            'balance_base' => (string) ($i + 1).'.000000',
            'display_unit_id' => $g->id,
            'created_by' => $creator->id,
            'created_at' => $now,
            'row_hash' => str_pad((string) $i, 64, '0', STR_PAD_LEFT),
        ];

        if (count($rows) === 500) {
            DB::table('stock_ledger')->insert($rows);
            $rows = [];
        }
    }
    if ($rows !== []) {
        DB::table('stock_ledger')->insert($rows);
    }

    return [$item, $g];
}

test('a filtered ledger under the async threshold still renders inline as before', function () {
    Queue::fake();
    [$item] = seedManyLedgerRows(10);
    $scientist = scientistUser();

    $response = $this->actingAs($scientist)->get(route('items.ledger.export.pdf', $item));

    $response->assertOk();
    $response->assertHeader('Content-Type', 'application/pdf');
    Queue::assertNothingPushed();
});

test('a filtered ledger over the async threshold is queued instead of rendered inline', function () {
    Queue::fake();
    [$item] = seedManyLedgerRows(5001);
    $scientist = scientistUser();

    $response = $this->actingAs($scientist)->get(route('items.ledger.export.pdf', $item));

    $export = LedgerExportRequest::where('item_id', $item->id)->firstOrFail();
    $response->assertRedirect(route('ledger-exports.show', $export));
    expect($export->status)->toBe('PENDING');
    expect($export->requested_by)->toBe($scientist->id);
    Queue::assertPushed(GenerateLedgerPdfExportJob::class);
});

test('the queued job renders the PDF, marks the export READY, and notifies the requester', function () {
    Mail::fake();
    [$item] = seedManyLedgerRows(5001);
    $scientist = scientistUser();

    $this->actingAs($scientist)->get(route('items.ledger.export.pdf', $item));
    $export = LedgerExportRequest::where('item_id', $item->id)->firstOrFail();

    (new GenerateLedgerPdfExportJob($export->id))->handle(
        app(Fr03PdfService::class),
        app(NotificationService::class),
    );

    $export->refresh();
    expect($export->status)->toBe('READY');
    expect($export->file_path)->not->toBeNull();
    expect(Storage::disk('ledger_exports')->exists($export->file_path))->toBeTrue();
    expect(Notification::where('user_id', $scientist->id)->where('type', 'ledger.export_ready')->exists())->toBeTrue();
    Mail::assertQueued(NotificationMail::class, fn ($mail) => $mail->hasTo($scientist->email));
});

test('ST-04/IDOR: a user who did not request the export cannot view it', function () {
    Queue::fake();
    [$item] = seedManyLedgerRows(5001);
    $requester = scientistUser();
    $otherUser = scientistUser();

    $this->actingAs($requester)->get(route('items.ledger.export.pdf', $item));
    $export = LedgerExportRequest::where('item_id', $item->id)->firstOrFail();

    $this->actingAs($otherUser)->get(route('ledger-exports.show', $export))->assertStatus(403);
    $this->actingAs($requester)->get(route('ledger-exports.show', $export))->assertOk();
});

test('the export requester can download the file once it is READY', function () {
    Queue::fake();
    [$item] = seedManyLedgerRows(5001);
    $scientist = scientistUser();

    $this->actingAs($scientist)->get(route('items.ledger.export.pdf', $item));
    $export = LedgerExportRequest::where('item_id', $item->id)->firstOrFail();

    (new GenerateLedgerPdfExportJob($export->id))->handle(
        app(Fr03PdfService::class),
        app(NotificationService::class),
    );

    $response = $this->actingAs($scientist)->get(route('ledger-exports.show', $export->fresh()));
    $response->assertOk();
    $response->assertHeader('Content-Type', 'application/pdf');
});
